services:
  app:
    image: ghcr.io/rknightion/paperless-ngx-dedupe:latest
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ./docker-data:/app/data
    env_file:
      - .env
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    stop_grace_period: 30s
